sudo: required
services:
    - docker

before_install:
    - docker build -t pavantekal/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true pavantekal/react-test npm test

after_success:
    - docker build -t pavantekal/multi-docker-client ./client
    - docker build -t pavantekal/multi-docker-nginx  ./nginx
    - docker build -t pavantekal/multi-docker-server ./server
    - docker build -t pavantekal/multi-docker-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push pavantekal/multi-docker-client
    - docker push pavantekal/multi-docker-nginx
    - docker push pavantekal/multi-docker-server
    - docker push pavantekal/multi-docker-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-572220341741
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
